module ApplicationHelper
  def title
    default = "this title was generated by the helper page"
    if @title.nil?
      default.capitalize
    else
      "#{default} - [#{@title.capitalize}]"
    end
  end

  def gravatar_for user,options = {:size=>40}
    if options[:class].blank?
      cclass = "img-circle"
    else
      cclass = options[:class]
    end
    gravatar_image_tag user.email.downcase,
    :class=>cclass,
    :alt=>user.name.capitalize,
    :gravatar=>options,
    :style => options[:style] unless options[:style].blank?
  end

  # just a simple function used inside the footer of each page
  def creator
    "Made by ROUINEB Hamza. 2016"
  end
end
