module ApplicationHelper
  def title
    default = "this title was generated by the helper page"
    if @title.nil?
      default.capitalize
    else
      "#{default} - [#{@title.capitalize}]"
    end
  end

end
