module ApplicationHelper
  def title
    default = "this title was generated by the helper page"
    if @title.nil?
      default.capitalize
    else
      "#{default} - [#{@title.capitalize}]"
    end
  end
  # just a simple function used inside the footer of each page
  def creator
    "Made by ROUINEB Hamza. 2016"
  end


end
